version: "3.3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/database:/var/lib/mysql      
    ports:
        - 33060:3306
    environment:
      MYSQL_DATABASE: cartoleiro
      MYSQL_ROOT_PASSWORD: ect4TIOZ3W9OKwp0
  app:
    build: .
    container_name: app
    restart: always
    command: "tail -f /dev/null"
    volumes:
      - ./:/home/deploy
    ports:
      - "80:80"
    depends_on:
      - "mysql"
