import React from 'react';
import { amount } from '../../utils/helpers';


import {
  Container,
  Title,
  Content,
  Item,
  Header,
  Shield,
  Info,
  Teams,
  Time,
  Players,
  Player,
  Photo,
  NameScouts,
  Name,
  Scouts,
  Scout,
  Score,
  Total,
  Text,
} from './styles';

import { Message } from '../../utils/styles';

function matches() {

  const data = {
    "scouts": [
      {
        "sigla": "A",
        "nome": "Assistência",
        "tipo": "Positivo"
      },
      {
        "sigla": "DE",
        "nome": "Defesas",
        "tipo": "Positivo"
      },
      {
        "sigla": "PS",
        "nome": "Pênalti sofrido",
        "tipo": "Positivo"
      },
      {
        "sigla": "DP",
        "nome": "Defesa pênalti",
        "tipo": "Positivo"
      },
      {
        "sigla": "SG",
        "nome": "Sem sofrer gol",
        "tipo": "Positivo"
      },
      {
        "sigla": "FS",
        "nome": "Falta sofrida",
        "tipo": "Positivo"
      },
      {
        "sigla": "DS",
        "nome": "Desarmes",
        "tipo": "Positivo"
      },
      {
        "sigla": "FF",
        "nome": "F. para fora",
        "tipo": "Positivo"
      },
      {
        "sigla": "FD",
        "nome": "F. defendida",
        "tipo": "Positivo"
      },
      {
        "sigla": "FT",
        "nome": "F. na trave",
        "tipo": "Positivo"
      },
      {
        "sigla": "G",
        "nome": "Gol",
        "tipo": "Positivo"
      },
      {
        "sigla": "FC",
        "nome": "Falta cometida",
        "tipo": "Negativo"
      },
      {
        "sigla": "GC",
        "nome": "Gol contra",
        "tipo": "Negativo"
      },
      {
        "sigla": "I",
        "nome": "Impedimento",
        "tipo": "Negativo"
      },
      {
        "sigla": "CA",
        "nome": "Cartão amarelo",
        "tipo": "Negativo"
      },
      {
        "sigla": "CV",
        "nome": "Cartão vermelho",
        "tipo": "Negativo"
      },
      {
        "sigla": "GS",
        "nome": "Gol sofrido",
        "tipo": "Negativo"
      },
      {
        "sigla": "PP",
        "nome": "Pênalti perdido",
        "tipo": "Negativo"
      },
      {
        "sigla": "PC",
        "nome": "Pênalti cometido",
        "tipo": "Negativo"
      }
    ],
    "time": {
      "id": 262,
      "nome": "Flamengo",
      "abreviacao": "FLA",
      "posicao": null,
      "escudo": "iVBORw0KGgoAAAANSUhEUgAAAEEAAABBCAYAAACO98lFAAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDIgNzkuMTYwOTI0LCAyMDE3LzA3LzEzLTAxOjA2OjM5ICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+nhxg7wAACIFJREFUeJzVm2lsVNcZhp97PJ7xNngZM8NicHAMxgYaKgpOHEgTFtOQtE2UNEujEiGRKm1+NEpStaUtKKQpaUQoVdtg0daKEkIEolACRCyiFpBCIEICamRjMMb24A3beOzZPMu5/WGb2CUzc2d8x8sjXcn2ud+573nn3LN8Z6wQAoH4HMgJVT7OsEvk4lCFhjCBOUCu/nrGHuFMAGBP4VRSE8Rdf0/Ny8fb0kzQ7Yrpwa9ca+G61x9TrN5ENCEUWcUlFK7biBoIEPR6AOhtv4Xz6hXajh+h5fBB1GBAN6HxJGYTmg/+i5wnn8XdWA9CEHS7UKXE+vBybCseZcban3Dh1Zdx19fpqTcu3N3PtQQZjUx5/EmEyYStdBW25d/BPKuQ6t9v4OSKEpr27yEtv4CFH+zGZJ10J85oyWZC4VzdxOtF1D0heeo05v+xDHPhHFx1tTj+e5EJc+ZiMJu5b8v7mLKt+Lo66am6jLlwDnM3vkvA7cJkycZcOIdrf95Md1VlPNoSM1H1BKMlmwV/20FiVhZnX3gCj72BJJuN00+U0lNTTfOh/ZhnF5GWl0/XhfMAWB58iKDbTVpBEQnJKfg6O4fUmZog4nppIaqeULRhE8mTp3Lm6Udx1l7FZJ2EyToJV10tl3/7c8yzZgPQevQz6srLmPb8agC6Lpyn5fCnFG14h7aKY0Pq3FM4NRoJUeEKSp6uuhnxPs0mZC28H+sjK2g6sBdn7dW7yv2OriG/q4G+mcFReRH7np0Y0tI4t/qpmKfUeKLJBGE0MvO1XwHQcfqUporNRX0DYOMnHwIQcDoJOJ2xaIw7ml6anB+8QPrc+wAIOHsiBygKM9a8THdVJc2H9gNgSEuLXWWc0dQTbp04zuxfrAdFwZRtvat87u/eo7etBU+THXd9HVnFD+JurMfTZKfgjXUk50zHVVdLzZZNujdADzSZ4LE30FZxDOvSUqzLSrHv2Tmk3PLAYowWC0qCga4L5wl63JgLihAGAyarDQDn9bvHkbGC5imyZvPbBL0eshc/jKVkyZCyE8uKqVg8nyvvbmRC4RxME62ceWolJ5YV8+WaZ1GlpO34Ed3F60VCqAIF5VUg45mJEzAKBX+3A3ddLbbSVViXrsRjbyB1Rh4p03Kp3bYV6fMhjEYSzelkLijGnD+LlsMH8TbZcV6tpvOL/wyp/7NOJ7cDktLMVFxSxuVyBCSHOp0ADhV1a+i2hkAgbgC5/7+LtJQsYe5bmzFZbbjqanE31uOqqyU1dwZBrxfrspV0nD7JxG8vo/oPG2nYUf619Y/wLrJeIu8JVRj13qHj9Ck+/+5Sqt76Ne6GG6RMy8Vy/2Kkz0dP1WVEYiLepps4r9VQ8Po6shY9cCc2ISU1tibEmZg2UEG3i8bdH5NknYSSkMDZ57/Hxdd/irO2BgBVlVT+5g1QYMH2j5j/p+186+8fM/mx7+sqXi9iMgEgyTaZtILZpEy/hwlF8wDuDJjp875J9+VLXPvLFpQEA9alpSSmZ9L06T/1Ua0zMZuQmpeP80o10u9n5mu/RJiSQFHwtjaTdm8+ttJV1P1jG42ffMjNvbv4cs0zyN5ePbXrRsSBcXOelWQRs1ch2dTYjr13xDJPYQfGiCbEQdBoENaEiCvGRzJSMCghvRrTBFSVii53xPsimvDK5EzNyYmxhisoNZkwPlunMxFN8KrqSOiIC1q1hzMhABAcxyYM0h52GgpnghPAHRy/JgzSHjalFc6EHoCeoNRJ0sjT/ZX2sOmwcCY0ArT7gzpJGnk6vtLeGO6+cFNkA8CpbjeO4Pg04pLrzjK9Idx94Uy4DnCm28OZbo9OskaN6+EKw70OF3QWMpqEbUu4vUMyfQNKyBTcOCEImCUyZHcO2RP6g8bWyWlsVIYzACKvGI/rKGa0iNiGSCYci1A+HojYhrB75P5x4RYwNjOkkXEBEyO9DmG30hLpEYgDwHOLzMksSU/WU2DcOOXwcK7HA3AgkgGg7RhuJ/Bck8/P8ozs4eobEXbd6h74cWe4+wbQkk84ArTYewNUusZmonQwla7egdxlC33aIxLRBIn0AWUA+zo0HMuPMoM0lvVrj4jWzFIZ4D/T7RnJDHHU2HsDA0t8P/0fnBY0mSCRrUC5Cuxoc8QkcCTY0eagP4NQ3q9ZE9HkGN8GvCcd7jHzddzBXPf6OelwA3jp06oZzSZIZCNQpgLbmm9HJXAk2NZ8e6AXlPVr1UxUBwoCkQFcAayzU4wYx8h5hE9VqXb7ANqAAonsihAyPARitUCoY/RaHUubov4oBUKhb/5dEcsD48gxYKVERp0Zjqk/C8QU4BJgiSU+DnQA35DIpliCYzqB6n/YS7HExomXYjUAhpE1UlGrFRQTsCTizfFlk0T+ddSeLhCKQOwbxYFwX/8YNSyGXYFApAD/BoqHW1eUnAWWSmTkY+cI6DLRC0Q6cBRYNMVoYENuNhaDvvnZjkCQN+vbafIFAM4BpRKpyxpet9XOYCMmGQ28mZvNdFOiLnU39PpZX99OaxwMAB3T6Spqr4KyE5jvDMpZFQ43uUmJ5AzTiC96PKy/0U5XIAhwCHhcInX9nwFd+6yK6ldQdgHZflVdeMLhpleFeakmRJRL7ICqUt7qoKy5C3/fEfv7wItacwTRELfFv0D8ENgOpN6bZORnUzOZmWzUFHvV42Przc6B3aoL+LFEakqVxUJcd0ACUQh8BCwQCjyWmcaLtvSQ34FyBSUftDo41Okc2BGeB34kkVXx1BnXIzYVtV1BKQecKjxU4/EZjna5EcCMJOOdb8V5pcr+Difv2DsHTpJ7gXXAWolsi6fGEUUg8gRi98BCJyPBoK61ZaprbZlqRoJh8AJot0DkjbbeuCIQJQJR8TWrvwqBKBltfSOKQBQLxN7+a6RXm0P4Hw++otZ3dpcCAAAAAElFTkSuQmCC",
      "60x60": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-65.png",
      "45x45": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-45.png",
      "30x30": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
      "created_at": "2022-03-11 06:07:32",
      "updated_at": "2022-09-09 10:00:04"
    },
    "posicao": {
      "id": 5,
      "nome": "Atacante",
      "abreviacao": "ata",
      "created_at": "2020-07-21 17:10:27",
      "updated_at": "2020-07-21 17:10:27"
    },
    "confrontos": [
      {
        "id": 293,
        "confronto": "Athlético-PR x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2019/09/09/Athletico-PR-30x30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "3",
        "partida_data": "23/04 16:30",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_jLJg754.png",
            "apelido": "Pablo",
            "pontuacao": -0.6,
            "A": 1,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_7POtFfh.png",
            "apelido": "Marcelo Cirino",
            "pontuacao": 1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 3,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 1,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_VXCkQFM.png",
            "apelido": "Canobbio",
            "pontuacao": 4.8,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 2,
            "FS": 3,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 3,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 5.2
      },
      {
        "id": 354,
        "confronto": "Ceará x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2019/10/10/ceara-30x30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "6",
        "partida_data": "14/05 16:30",
        "atletas": [
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/02/22/391609eb9a9349eac73814c39b4be34c_50x50.png",
            "apelido": "Erick",
            "pontuacao": -0.30000000000000004,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 4,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/02/22/d2d6e5f9f0b8f9299ec51823ad4791c8_50x50.png",
            "apelido": "Zé Roberto",
            "pontuacao": 7,
            "A": 1,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 2,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/08/11/f19c59d4d6626b101ff291f3e852072d_50x50.png",
            "apelido": "Jô",
            "pontuacao": 9.2,
            "A": 0,
            "G": 1,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 1,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 3,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 15.899999999999999
      },
      {
        "id": 266,
        "confronto": "Fluminense x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2015/01/12/Fluminense-escudo.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "8",
        "partida_data": "29/05 18:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/04/20/49ddf4ceba0c02ddb6fc62fb80ffa3dd_50x50.png",
            "apelido": "Willian",
            "pontuacao": -0.30000000000000004,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/27/photo_50x50_zQfRwuQ.png",
            "apelido": "Cano",
            "pontuacao": 9,
            "A": 0,
            "G": 1,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 2,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 5,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2021/08/19/131f19bc697057f38a3c8ec99c785a97_50x50.png",
            "apelido": "Luiz Henrique",
            "pontuacao": 7.5,
            "A": 3,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 2,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 6,
            "PP": 0,
            "DS": 4,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/17/photo_220x220.png",
            "apelido": "John Kennedy",
            "pontuacao": -0.5,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 1,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/04/20/f6b7d6073f1d67e5e9263e986f470c8b_50x50.png",
            "apelido": "Matheus Martins",
            "pontuacao": 4.1,
            "A": 5,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 2,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 19.799999999999997
      },
      {
        "id": 280,
        "confronto": "Bragantino x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2020/01/01/30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "10",
        "partida_data": "08/06 20:30",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/05/05/5c98a0d6cc76edfef83280072bbd3832_50x50.png",
            "apelido": "Artur",
            "pontuacao": 3.7,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 1,
            "FS": 3,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 10,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/05/05/c2e17a280e19cf13328cce44f755ed84_50x50.png",
            "apelido": "Ytalo",
            "pontuacao": 2.2,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 1,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/05/05/d0de5e463c8123423e2713cdde571faf_50x50.png",
            "apelido": "Helinho",
            "pontuacao": 2.1,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 2,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 6,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 8
      },
      {
        "id": 285,
        "confronto": "Internacional x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2016/05/03/inter30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "11",
        "partida_data": "11/06 21:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/07/photo_50x50_TAoUoam.png",
            "apelido": "Wanderson",
            "pontuacao": 17.1,
            "A": 0,
            "G": 2,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 5,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/07/photo_50x50_Ymwr1lY.png",
            "apelido": "Alemão",
            "pontuacao": 3.4,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 1,
            "FF": 1,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/04/12/5422d339b6546dc0505e80e10b027269_50x50.png",
            "apelido": "Pedro Henrique",
            "pontuacao": 9,
            "A": 0,
            "G": 1,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 1,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 29.5
      },
      {
        "id": 282,
        "confronto": "Atlético-MG x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2017/11/23/Atletico-Mineiro-escudo30px.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "13",
        "partida_data": "19/06 16:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/01/photo_50x50_HgdfwiM.png",
            "apelido": "Hulk",
            "pontuacao": 6.7,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 3,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 4,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/01/photo_50x50_yFYmdoD.png",
            "apelido": "Vargas",
            "pontuacao": -1.3,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/01/photo_50x50_9wKfftZ.png",
            "apelido": "Ademir",
            "pontuacao": 6.7,
            "A": 0,
            "G": 1,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/01/photo_50x50_o8gTFxZ.png",
            "apelido": "Eduardo Sasha",
            "pontuacao": 0,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 12.100000000000001
      },
      {
        "id": 277,
        "confronto": "Santos x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2014/04/14/santos_30x30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "15",
        "partida_data": "02/07 19:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_eb1ett7.png",
            "apelido": "Marcos Leonardo",
            "pontuacao": 2.8,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 1,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/03/03/720ce11785d74738c66fdb3f797d770b_50x50.png",
            "apelido": "Léo Baptistão ",
            "pontuacao": 5.1,
            "A": 1,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 1,
            "FS": 3,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 8,
            "PP": 0,
            "DS": 3,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_CqBwl6X.png",
            "apelido": "Ângelo",
            "pontuacao": 1.5,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 1,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 5,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_jbahd9z.png",
            "apelido": "Lucas Braga",
            "pontuacao": 5.6,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 2,
            "FF": 2,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 6,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/03/03/87ee12224aa1dccc15149c42181e9432_50x50.png",
            "apelido": "Rwan",
            "pontuacao": 1.9,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 16.9
      },
      {
        "id": 264,
        "confronto": "Corinthians x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2019/09/30/Corinthians_30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "16",
        "partida_data": "10/07 16:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/02/photo_50x50_39SGFR6.png",
            "apelido": "Róger Guedes",
            "pontuacao": 2.7,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 3,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 6,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/02/photo_50x50_odfm6XT.png",
            "apelido": "Gustavo Mosquito",
            "pontuacao": 2.5,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 4,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/02/photo_50x50_TquvINB.png",
            "apelido": "Giovane",
            "pontuacao": -0.5,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 4.7
      },
      {
        "id": 314,
        "confronto": "Avaí x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2018/09/04/escudo-avai-30x30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "19",
        "partida_data": "24/07 11:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/04/08/c60eb6c17dd46f0a98ac8d236bddbbd7_50x50.png",
            "apelido": "Bissoli",
            "pontuacao": 0.6,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 5,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/04/14/6351c93f1e7d0b3514916390f48db891_50x50.png",
            "apelido": "Marcinho",
            "pontuacao": 3.2,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 1,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/07/18/928d4688872689cf9875b1e26a3d4fd9_50x50.png",
            "apelido": "Nathan",
            "pontuacao": 0,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 3.8000000000000003
      },
      {
        "id": 276,
        "confronto": "São Paulo x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2014/04/14/sao_paulo_30x30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "21",
        "partida_data": "06/08 20:30",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/08/photo_50x50_zc5jjjt.png",
            "apelido": "David",
            "pontuacao": -0.19999999999999996,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/03/01/3abaa943f1546750dd057d6cb3559ce5_50x50.png",
            "apelido": "Calleri",
            "pontuacao": 3,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 2,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/01/photo_50x50_0I7WXAm.png",
            "apelido": "Erison",
            "pontuacao": 1.2,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 4,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/06/28/beaa874f9953e86894fb3ff1e44fd934_50x50.png",
            "apelido": "Marcos Guilherme",
            "pontuacao": 2.4,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 2,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 4,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/16/photo_50x50.png",
            "apelido": "Pedrinho",
            "pontuacao": 11.2,
            "A": 0,
            "G": 1,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 7,
            "PP": 0,
            "DS": 3,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 17.6
      },
      {
        "id": 275,
        "confronto": "Palmeiras x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2014/04/14/palmeiras_30x30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "23",
        "partida_data": "21/08 16:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/15/photo_50x50_eJOedW8.png",
            "apelido": "Rony",
            "pontuacao": 1.4,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 1,
            "FF": 1,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 5,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/15/photo_50x50_dKDb4Xe.png",
            "apelido": "Dudu",
            "pontuacao": 9.7,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 1,
            "FS": 5,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 10,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/15/photo_50x50_V15s07E.png",
            "apelido": "José López",
            "pontuacao": 0.6,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 1,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 2,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 11.7
      },
      {
        "id": 263,
        "confronto": "Botafogo x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2019/02/04/botafogo-30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "24",
        "partida_data": "28/08 18:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/07/photo_50x50_t9xgUxE.png",
            "apelido": "Victor Sá",
            "pontuacao": 1.1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 7,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://storage.googleapis.com/bkt-gglobo-sde-hdg-prd-sdeadmin_prod/media/person_role/2022/06/16/01982dd5226684462ec07bec6dffd11b_50x50.png",
            "apelido": "Jeffinho",
            "pontuacao": 6.4,
            "A": 3,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 2,
            "FF": 2,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 4,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/15/photo_50x50_XMfC6C1.png",
            "apelido": "Luis Henrique",
            "pontuacao": -0.19999999999999996,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 2,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 7.3
      },
      {
        "id": 290,
        "confronto": "Goiás x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2021/03/01/goias-30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "26",
        "partida_data": "11/09 19:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/11/photo_50x50_onOMJJv.png",
            "apelido": "Alesson",
            "pontuacao": 0,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/11/photo_50x50_ARVnYib.png",
            "apelido": "Vinicius",
            "pontuacao": -1.4,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/04/05/aaad5989249282ee07375a4f7b9bf1da_50x50.png",
            "apelido": "Renato Junior",
            "pontuacao": 2.8,
            "A": 1,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 1.4
      },
      {
        "id": 356,
        "confronto": "Fortaleza x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2021/09/19/30_0000_Fortaleza-2021.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "28",
        "partida_data": "28/09 19:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/05/12/c5b6ac96aea31d2271156591230c8f4c_50x50.png",
            "apelido": "Silvio Romero",
            "pontuacao": -0.30000000000000004,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/09/28/photo_50x50_wjBokpm.png",
            "apelido": "Pedro Rocha",
            "pontuacao": 15.5,
            "A": 0,
            "G": 2,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 2,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 3,
            "PI": 5,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/05/12/f14daa299b1fbfb010af7e0468342ccd_50x50.png",
            "apelido": "Moisés",
            "pontuacao": 4.6,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 1,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 3,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/05/12/f45da0b069dc4c621269c6f7735e27e6_50x50.png",
            "apelido": "Depietri",
            "pontuacao": -0.19999999999999996,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 2,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/07/16/27deb38ffaefdd66a10d7f246dcc678f_50x50.png",
            "apelido": "Thiago Galhardo",
            "pontuacao": 3.1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 0,
            "FS": 4,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/13/photo_50x50_TyD4lcH.png",
            "apelido": "Júnior Santos",
            "pontuacao": 9.1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 4,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 6,
            "PP": 0,
            "DS": 5,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 31.799999999999997
      },
      {
        "id": 1371,
        "confronto": "Cuiabá x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2014/04/16/cuiaba30_.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "31",
        "partida_data": "08/10 19:00",
        "atletas": [
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/02/23/4ba86feb09facb90b3a01b1712c3c8f5_50x50.png",
            "apelido": "André Luís",
            "pontuacao": 6.1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 1,
            "FS": 4,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 3,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/06/photo_50x50_AvLd8xm.png",
            "apelido": "Deyverson",
            "pontuacao": 6.3,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 2,
            "FF": 2,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 7,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/06/photo_50x50_LlMyePJ.png",
            "apelido": "Isidro Pitta",
            "pontuacao": 6.7,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 1,
            "FF": 4,
            "FS": 4,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 5,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 19.099999999999998
      },
      {
        "id": 327,
        "confronto": "América-MG x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2019/02/28/escudo30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "33",
        "partida_data": "22/10 19:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/03/08/photo_50x50_8mUcFok.png",
            "apelido": "Wellington Paulista",
            "pontuacao": -0.4,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/02/25/32fc5d9f18e690ed6ef80d16faae95cc_50x50.png",
            "apelido": "Felipe Azevedo",
            "pontuacao": 1.9,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 7,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/02/25/f952435e80bcd6628e6480a7ad0ed047_50x50.png",
            "apelido": "Henrique Almeida",
            "pontuacao": -0.30000000000000004,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/02/25/561f3ca4238e82e1b2e1479a1a66c551_50x50.png",
            "apelido": "Everaldo",
            "pontuacao": 10.4,
            "A": 0,
            "G": 1,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 1,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 7,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/03/31/a411b722d7d0edc88f871c1a48191dc1_50x50.png",
            "apelido": "Aloísio",
            "pontuacao": -1.2,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 1,
            "PI": 3,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2022/08/10/2c133460f6f214aed522ba40302a5c33_50x50.png",
            "apelido": "Mastriani",
            "pontuacao": 0.1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 10.5
      },
      {
        "id": 294,
        "confronto": "Coritiba x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2017/03/29/coritiba30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "36",
        "partida_data": "06/11 16:00",
        "atletas": [
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_o07AeW3.png",
            "apelido": "Alef Manga",
            "pontuacao": 10.1,
            "A": 0,
            "G": 1,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 5,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/02/23/4b8edf6d0d6b8c3a3c39de67b5bd75e1_50x50.png",
            "apelido": "Léo Gamalho",
            "pontuacao": -0.09999999999999998,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 0,
            "FS": 1,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 2,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_qDCu3iB.png",
            "apelido": "Matheus Cadorini",
            "pontuacao": 0.6,
            "A": 0,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 1,
            "FD": 0,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 5,
            "PP": 0,
            "DS": 2,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.sde.globo.com/media/person_role/2023/02/28/photo_50x50_6f5bwYY.png",
            "apelido": "Fabrício Daniel",
            "pontuacao": 1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 0,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 11.6
      },
      {
        "id": 286,
        "confronto": "Juventude x Flamengo",
        "escudo_casa": "https://s.sde.globo.com/media/organizations/2021/04/29/juventude30.png",
        "escudo_fora": "https://s.sde.globo.com/media/organizations/2018/04/09/Flamengo-30.png",
        "rodada": "37",
        "partida_data": "09/11 21:30",
        "atletas": [
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/03/03/9bdded7e0046ad8500605256f741994b_50x50.png",
            "apelido": "Capixaba",
            "pontuacao": 1.8,
            "A": 1,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 2,
            "FD": 0,
            "FF": 1,
            "FS": 3,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 1,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://s.glbimg.com/es/sde/f/2022/08/06/f016d3ea4f1bdceef28512d7bf47fd36_50x50.png",
            "apelido": "Felipe Pires",
            "pontuacao": -0.19999999999999996,
            "A": 2,
            "G": 0,
            "CA": 1,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 0,
            "FF": 0,
            "FS": 2,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 2,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          },
          {
            "foto": "https://storage.googleapis.com/bkt-gglobo-sde-hdg-prd-sdeadmin_prod/media/person_role/2022/08/29/photo_50x50_r7kZYAV.png",
            "apelido": "Ruan",
            "pontuacao": 1.1,
            "A": 0,
            "G": 0,
            "CA": 0,
            "CV": 0,
            "DP": 0,
            "FC": 0,
            "FD": 1,
            "FF": 0,
            "FS": 0,
            "FT": 0,
            "GC": 0,
            "GS": 0,
            "I": 0,
            "PI": 1,
            "PP": 0,
            "DS": 0,
            "SG": 0,
            "PS": 0,
            "PC": 0,
            "DE": 0
          }
        ],
        "pontuacao_total": 2.7
      }
    ]
  }

  return (
    <Container>
      {
        data.confrontos.length
          ?
          <>
            <Title>Pontuação cedida do time do {data.time.nome.toUpperCase()} para os {data.posicao.nome.toUpperCase()}.</Title>
            {
              data.confrontos.map(e =>
                <Item>
                  <Header>
                    <Shield src={e.escudo_casa} />
                    <Info>
                      <Teams>{e.confronto}</Teams>
                      <Time>{`${e.partida_data} - Rodada ${e.rodada}`}</Time>
                    </Info>
                    <Shield src={e.escudo_fora} />
                  </Header>
                  <Content>
                    {
                      e.atletas.map(e =>
                        <>
                          <Players>
                            <Player>
                              <Photo src={e.foto} />
                              <NameScouts>
                                <Name>{e.apelido}</Name>
                                <Scouts>
                                  {
                                    data.scouts.map(item =>
                                      <Scout value={e[item.sigla]} type={item.tipo}>{`${e[item.sigla]}${item.sigla}`}</Scout>
                                    )
                                  }
                                </Scouts>
                              </NameScouts>
                            </Player>
                            <Score value={e.pontuacao}>{amount(e.pontuacao)}</Score>
                          </Players>
                        </>
                      )
                    }
                    <Total>
                      <Text>Total:</Text>
                      <Score value={e.pontuacao_total}>{amount(e.pontuacao_total)}</Score>
                    </Total>
                  </Content>
                </Item>
              )
            }
          </>
          :
          <Message>Nenhum jogador encontrado</Message>
      }

    </Container >
  );
}

export default matches;